server:
  address:     ":8002"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

zmq:
  server : "tcp://192.168.1.55:35579"
  detect : "tcp://192.168.1.55:35580"

iotDb:
  host: "192.168.1.15"
  port: "6667"
  user: "root"
  password: "root"
  restPort: "18080"






